<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
    <RuntimeFrameworkVersion>10.0.10</RuntimeFrameworkVersion>
    <RollForward>Disable</RollForward>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <AssemblyName>Plasma.ManagedHost</AssemblyName>
    <RootNamespace>Plasma.ManagedHost</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Plasma.ScriptCore\Plasma.ScriptCore.csproj" />
  </ItemGroup>
</Project>
