#pragma once

#if PL_ENABLED(PL_COMPILE_ENGINE_AS_DLL)
#  ifdef BUILDSYSTEM_BUILDING_CSHARPPLUGIN_LIB
#    define PL_CSHARPPLUGIN_DLL PL_DECL_EXPORT
#  elif defined(BUILDSYSTEM_FOLDING_PLUGIN_IMPORTS)
#    define PL_CSHARPPLUGIN_DLL
#  else
#    define PL_CSHARPPLUGIN_DLL PL_DECL_IMPORT
#  endif
#else
#  define PL_CSHARPPLUGIN_DLL
#endif
